# Generated by Django 3.0.7 on 2020-06-07 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asaka', '0002_auto_20200605_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='creaate_date',
            new_name='create_date',
        ),
    ]
